version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"